save_val: true
model:
  gaussian:
    class_path: internal.models.aaags.Gaussian2D
    init_args:
      sh_degree: 3
      optimization:
        means_lr_init: 1.6e-5
        means_lr_scheduler:
          lr_final: 1.6e-6
          lr_final: 0.00000016
          max_steps: 25000 # 100000 // 4
  metric:
    class_path: internal.metrics.aaags_metricsv2.DistributedMetrics
    init_args:
      lambda_scale: 0.001
      sample_alpha: 1.0
      mono_thresh: 0.001
      patch_size: 5
      radius_increment: 1
      multi_view_from: 50000
      single_view_from: 0
      lambda_normal: 0.0125
      depth_loss_type: l1+ssim
      depth_loss_ssim_weight: 0.0
      depth_loss_weight:
        init: 0.5
        final_factor: 0.005
        max_steps: 30000
  renderer:
    class_path: internal.renderers.aaags_trimip_renderer.DistributedRenderer
    init_args:
      use_app: true
      use_app_time: true
      prune_ratio: 0.25
      diable_trimming: false
      contribution_prune_interval: 1500
      contribution_prune_from_iter: 1000
      redistribute_until: 30000
      appearance_optimization:
        max_steps: 25000
  density: 
    class_path: internal.density_controllers.aaags_anchor_density_controller.DistributedController
    init_args:
      voxel_size: 1
      voxel_thresh: 10
      pixel_thresh: 20
      densify_until_iter: 30000
      densify_from_iter: 500
      densification_interval: 300
      opacity_reset_interval: 6000
      densify_grad_threshold: 0.0001
trainer:
  strategy:
    class_path: internal.mp_strategy.MPStrategy
  devices: [3, 4, 5, 6]
  check_val_every_n_epoch: 5
  max_steps: 100000
data:
  use_multi_view: true
  batch_size: 4
  path: data/mill19/building-pixsfm/train
  parser:
    class_path: internal.dataparsers.estimated_mask_depth_colmap_dataparser.EstimatedDepthColmap
    init_args:
      additional_ply_path: add_ply/building.ply
      overwrite_val_path: data/mill19/building-pixsfm/val
      eval_image_select_mode: ratio
      eval_ratio: 0.1
      down_sample_factor: 4.0
save_iterations:
- 100000