save_val: false
model:
  gaussian:
    class_path: internal.models.aaags.Gaussian2D
    init_args:
      sh_degree: 2
      optimization:
        means_lr_scheduler:
          max_steps: 20000 # optimization's max_steps is divide by bsz
  metric:
    class_path: internal.metrics.aaags_metricsv2.DistributedMetrics
  renderer:
    class_path: internal.renderers.aaags_trimip_renderer.DistributedRenderer
    init_args:
      use_app: false
      use_app_time: false
      use_app_robust: true
      k_overlap: 30
      diable_trimming: false
      appearance_optimization:
        max_steps: 20000 # optimization's max_steps is divide by bsz
        warm_up: 0
  density: 
    class_path: internal.density_controllers.aaags_anchor_density_controller.DistributedController
trainer:
  strategy:
    class_path: internal.mp_strategy.MPStrategy
  devices: [2]
data:
  path: data/matrix_city/aerial/train/block_all
  parser:
    class_path: internal.dataparsers.estimated_mask_depth_colmap_dataparser.EstimatedDepthColmap
    init_args:
      overwrite_val_path: data/matrix_city/aerial/test/block_all_test
      split_mode: reconstruction
      down_sample_factor: 1.2