save_val: false
model:
  gaussian:
    class_path: internal.models.aaags.Gaussian2D
    init_args:
      sh_degree: 2
      optimization:
        means_lr_scheduler:
          max_steps: 20000 # optimization's max_steps is divide by bsz
  metric:
    class_path: internal.metrics.aaags_metricsv2.DistributedMetrics
  renderer:
    class_path: internal.renderers.aaags_trimip_renderer.DistributedRenderer
    init_args:
      use_app: true
      use_app_time: false
      # aabb: [-1108.8165283203125, -660.6905517578125, -30.39513397216797, 311.8224182128906, 208.13633728027344, 58.65856170654297]
      aabb: [-950, -650, -5, 200, 300, 100]
      diable_trimming: true
      appearance_optimization:
        max_steps: 20000 # optimization's max_steps is divide by bsz
        warm_up: 0
  density: 
    class_path: internal.density_controllers.aaags_anchor_density_controller.DistributedController
trainer:
  strategy:
    class_path: internal.mp_strategy.MPStrategy
  devices: [0]
data:
  path: data/matrix_city/street/train/block_A
  parser:
    class_path: internal.dataparsers.estimated_mask_depth_colmap_dataparser.EstimatedDepthColmap
    init_args:
      # overwrite_val_path: data/matrix_city/street/test/block_A_test
      split_mode: reconstruction
      eval_image_select_mode: ratio
      eval_ratio: 1