save_val: true
model:
  gaussian:
    class_path: internal.models.aaags.Gaussian2D
    init_args:
      sh_degree: 3
      optimization:
        means_lr_scheduler:
          max_steps: 12500 # 100000 // 4
  metric:
    class_path: internal.metrics.aaags_metricsv2.DistributedMetrics
  renderer:
    class_path: internal.renderers.aaags_trimip_renderer.DistributedRenderer
    init_args:
      use_app: true
      # use_app_robust: true
      use_app_time: true
      aabb: [-235.7144012451172, 13.641380310058594, -231.222900390625, 210.5653839111328, 92.20113372802734, 93.20800018310547]
  density: 
    class_path: internal.density_controllers.aaags_anchor_density_controller.DistributedController
trainer:
  strategy:
    class_path: internal.mp_strategy.MPStrategy
  devices: [1]
  check_val_every_n_epoch: 5
  max_steps: 100000
data:
  path: data/urban_scene_3d/sci-art-pixsfm/train
  parser:
    class_path: internal.dataparsers.estimated_mask_depth_colmap_dataparser.EstimatedDepthColmap
    init_args:
      overwrite_val_path: data/urban_scene_3d/sci-art-pixsfm/val
      eval_image_select_mode: ratio
      eval_ratio: 0.1
      down_sample_factor: 4.0