save_val: false
model:
  gaussian:
    class_path: internal.models.metrogs.Gaussian2D
    init_args:
      sh_degree: 3
      optimization:
        means_lr_init: 1.6e-5
        means_lr_scheduler:
          lr_final: 0.00000064
          max_steps: 25000 # 100000 // 4
  metric:
    class_path: internal.metrics.metrogs_metrics.DistributedMetrics
    init_args:
      lambda_scale: 0.001
      mono_thresh: 0.001
      patch_size: 5
      radius_increment: 1
      multi_view_from: 50000
      single_view_from: 0
      lambda_normal: 0.0125
      depth_loss_type: l1+ssim
      depth_loss_ssim_weight: 0.0
      depth_loss_weight:
        init: 0.5
        final_factor: 0.005
        max_steps: 30000
  renderer:
    class_path: internal.renderers.metrogs_renderer.DistributedRenderer
    init_args:
      use_app: true
      use_app_time: true
      prune_ratio: 0.12
      diable_trimming: false
      contribution_prune_interval: 5000
      contribution_prune_from_iter: 1000
      redistribute_until: 30000
      appearance_optimization:
        max_steps: 25000
  density: 
    class_path: internal.density_controllers.metrogs_density_controller.DistributedController
    init_args:
      voxel_size: 0.1
      voxel_thresh: 10
      pixel_thresh: 20
      densify_until_iter: 30000
      densify_from_iter: 500
      densification_interval: 600
      opacity_reset_interval: 6000
      densify_grad_threshold: 0.0001
trainer:
  strategy:
    class_path: internal.mp_strategy.MPStrategy
  devices: [0,1,2,3]
  check_val_every_n_epoch: 5
  max_steps: 100000
data:
  use_multi_view: true
  batch_size: 4
  path: data/urban_scene_3d/residence-pixsfm/train
  parser:
    class_path: internal.dataparsers.estimated_mask_depth_colmap_dataparser.EstimatedDepthColmap
    init_args:
      additional_ply_path: add_ply/residence.ply
      overwrite_val_path: data/urban_scene_3d/residence-pixsfm/val
      split_mode: reconstruction
      down_sample_factor: 4.0
save_iterations:
- 100000