save_val: false
model:
  gaussian:
    class_path: internal.models.metrogs.Gaussian2D
    init_args:
      sh_degree: 2
  metric:
    class_path: internal.metrics.metrogs_metrics.DistributedMetrics
  renderer:
    class_path: internal.renderers.metrogs_renderer.DistributedRenderer
    init_args:
      use_app: true
      # use_app_robust: true
  density:
    class_path: internal.density_controllers.metrogs_density_controller.DistributedController
trainer:
  strategy:
    class_path: internal.mp_strategy.MPStrategy
  devices: [0]
data:
  path: data/matrix_city/street/train/block_A
  parser:
    class_path: internal.dataparsers.estimated_mask_depth_colmap_dataparser.EstimatedDepthColmap
    init_args:
      overwrite_val_path: data/matrix_city/street/test/block_A_test
      split_mode: reconstruction